# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4Hek_E8EIhQMIHmdQVa92dS2UHl0bVi
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler



processed_path = "/content/drive/MyDrive/smog_project/processed/cleaned_data_ml.csv"
df = pd.read_csv(processed_path)

X = df.drop(columns=['AQI']).values
y_real = df['AQI'].values.reshape(-1,1)

from sklearn.model_selection import train_test_split

# Correct syntax
X_train, X_test, y_train_real, y_test_real = train_test_split(
    X, y_real, test_size=0.2, random_state=42
)

scaler = StandardScaler()
y_scaled = scaler.fit_transform(y_real)

# Save mean and std for reversing later
y_mean = scaler.mean_[0]
y_std = np.sqrt(scaler.var_[0])

scaler = StandardScaler()
y_train_scaled = scaler.fit_transform(y_train_real)

# Save mean and std to reverse predictions
y_mean = scaler.mean_[0]
y_std = np.sqrt(scaler.var_[0])

model = LinearRegression()
model.fit(X_train, y_train_scaled)

y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)

y_train_pred_real = y_train_pred_scaled * y_std + y_mean
y_test_pred_real = y_test_pred_scaled * y_std + y_mean

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train_real, y_train_pred_real, "Train")
evaluate(y_test_real, y_test_pred_real, "Test")

print("Test AQI min:", y_test_real.min(), "max:", y_test_real.max())
print("Test predictions min:", y_test_pred_real.min(), "max:", y_test_pred_real.max())

