# -*- coding: utf-8 -*-
"""DatasetCuration&Integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJuPY8aIQd9jXIsrfEOR08ix9BnzV1zH
"""

from google.colab import drive
drive.mount('/content/drive')

# ----------------- 2. Import Libraries -----------------
import pandas as pd
import numpy as np
import os

# ----------------- 3. Config: Paths -----------------
RAW_DIR = "/content/drive/MyDrive/smog_project/raw"
PROCESSED_DIR = "/content/drive/MyDrive/smog_project/processed"
os.makedirs(PROCESSED_DIR, exist_ok=True)

DATASET1_PATH = os.path.join(RAW_DIR, "AirQuality_1.csv")  # Dataset1
DATASET2_PATH = os.path.join(RAW_DIR, "AirQuality_2.csv")  # Dataset2
MERGED_PATH = os.path.join(PROCESSED_DIR, "Merged_AirQuality.csv")

df1 = pd.read_csv(os.path.join(RAW_DIR, "AirQuality_1.csv"))
df1_cols = ['City', 'Date', 'PM2.5', 'NO', 'CO', 'SO2', 'O3', 'AQI','Temperature','Humidity'.'Wind_speed','Rainfall']
df1 = df1[df1_cols].copy()

# Dataset2: more pollutants
df2 = pd.read_csv(os.path.join(RAW_DIR, "AirQuality_2.csv"))
df2_cols = ['City', 'Datetime', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx',
            'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene',
            'AQI', 'AQI_Bucket','Temperature','Humidity'.'Wind_speed','Rainfall']
df2 = df2[df2_cols].copy()

# ----------------- 5. Standardize Column Names -----------------
def clean_cols(df):
    df.columns = df.columns.str.strip().str.replace(' ', '_')
    return df

df1 = clean_cols(df1)
df2 = clean_cols(df2)

# Rename Datetime -> Date in df2
df2.rename(columns={'Datetime':'Date'}, inplace=True)

# Convert Date columns to datetime type
df1['Date'] = pd.to_datetime(df1['Date'], errors='coerce')
df2['Date'] = pd.to_datetime(df2['Date'], errors='coerce')

# Drop rows with invalid dates
df1 = df1.dropna(subset=['Date'])
df2 = df2.dropna(subset=['Date'])

# ----------------- 6. Merge Datasets -----------------
# Concatenate vertically, keeping all columns
df = pd.concat([df1, df2], ignore_index=True, sort=False)

# ----------------- 7. Handle Missing Values -----------------
# List of pollutants only in dataset2
extra_pollutants = ['PM10', 'NO2', 'NOx', 'NH3', 'Benzene', 'Toluene', 'Xylene']

# Impute missing pollutant values with city-level mean
for col in extra_pollutants:
    if col in df.columns:
        df[col] = df.groupby('City')[col].transform(lambda x: x.fillna(x.mean()))
        # fallback global mean if entire city is NaN
        df[col] = df[col].fillna(df[col].mean())

# Fill AQI_Bucket missing values for Dataset1 rows
if 'AQI_Bucket' in df.columns:
    df['AQI_Bucket'] = df['AQI_Bucket'].fillna('Unknown')

# ----------------- 8. Cleanup -----------------
df.reset_index(drop=True, inplace=True)

# ----------------- 9. Save Processed Dataset -----------------
df.to_csv(MERGED_PATH, index=False)
print("✅ Merged and preprocessed dataset saved at:", MERGED_PATH)

# ----------------- 10. Inspect Dataset -----------------
print("\nSample data:")
print(df.head())

print("\nColumns with remaining NaNs:")
print(df.isnull().sum())

print("\nDataset shape:", df.shape)

# =================== END: Data Integration & Preprocessing ===================

