# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdODRLotPsGX6dmDijyIaXLmellgsxqd
"""

# ---------- MOUNT GOOGLE DRIVE ----------
from google.colab import drive
drive.mount('/content/drive')

# ---------- IMPORT LIBRARIES ----------
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

# ---------- LOAD MERGED DATA ----------
data_path = "/content/drive/MyDrive/smog_project/processed/Merged_AirQuality.csv"
df = pd.read_csv(data_path)

# Ensure Date is datetime type
df['Date'] = pd.to_datetime(df['Date'])

# Check first few rows
df.head()

# Count missing values
print("Missing values per column:")
print(df.isnull().sum())

# Standardize city names
df['City'] = df['City'].str.strip().str.title()

# AQI_Bucket encoding (Good=0, Moderate=1, Poor=2, etc.)
df['AQI_Bucket_Code'] = df['AQI_Bucket'].astype('category').cat.codes

# City encoding (useful for ML models)
df['City_Code'] = df['City'].astype('category').cat.codes

# Extract day, month, weekday
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Weekday'] = df['Date'].dt.weekday  # 0=Monday, 6=Sunday

# Optional: season feature
def get_season(month):
    if month in [12,1,2]: return 'Winter'
    elif month in [3,4,5]: return 'Spring'
    elif month in [6,7,8]: return 'Summer'
    else: return 'Autumn'

df['Season'] = df['Month'].apply(get_season)
df['Season_Code'] = df['Season'].astype('category').cat.codes

# ---------- 6. Lag Features (Previous Day Pollutants / AQI) ----------

# Define pollutant columns present in your dataset
pollutants = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']

# Sort by City + Date to ensure correct temporal order
df = df.sort_values(['City', 'Date'])

# Create lag features (previous day) and rolling 3-day mean
for col in pollutants + ['AQI']:
    df[f'{col}_lag1'] = df.groupby('City')[col].shift(1)    # previous day
    df[f'{col}_roll3'] = df.groupby('City')[col].rolling(window=3, min_periods=1).mean().reset_index(0,drop=True)  # 3-day rolling average

# Check result
df.head()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[pollutants] = scaler.fit_transform(df[pollutants])

# Check first few rows
df.head()

# Save to processed folder for ML modeling
processed_path = "/content/drive/MyDrive/smog_project/processed/Merged_AQ_Processed.csv"
df.to_csv(processed_path, index=False)
print("Processed dataset saved to:", processed_path)
df = pd.read_csv(data_path)

print("Updated dataset saved with lag and rolling features.")
print("Columns now:", df.columns.tolist())

