# -*- coding: utf-8 -*-
"""FeatureControl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191H6CP6z_8Q-AQaZFUqU0sEuiRVrKCB8
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
merged_path = "/content/drive/MyDrive/smog_project/processed/air_quality_ml_ready.csv"
df = pd.read_csv(merged_path)

df.columns

# ---------- Correlation Heatmap --------
pollutants = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']

plt.figure(figsize=(12,10))
corr_cols = ['AQI'] + pollutants
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap: AQI and Pollutants")
plt.show()

# List of all pollutants in your data
all_pollutants = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'CO', 'NH3', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']

# Find all pollutant-related columns (raw, lag, roll, cityavg)
pollutant_cols = []

for col in df.columns:
    for pollutant in all_pollutants:
        if pollutant in col and col != 'AQI':  # Exclude AQI
            pollutant_cols.append(col)
            break

# Remove duplicates
pollutant_cols = list(set(pollutant_cols))
pollutant_cols = sorted(pollutant_cols)

print(f"\nFound {len(pollutant_cols)} pollutant-related columns:")
for i, col in enumerate(pollutant_cols, 1):
    print(f"  {i:2d}. {col}")

# Add AQI to the list
cols_to_use = pollutant_cols + ['AQI']

# Select only these columns
df_pollutants = df[cols_to_use].copy()

# Convert to numeric
for col in df_pollutants.columns:
    df_pollutants[col] = pd.to_numeric(df_pollutants[col], errors='coerce')

columns_to_remove = [
    # ========== IDENTIFIERS ==========
    'City',              # Use City_enc instead
    'Date',              # Use Month/Weekday/Day instead
    'Season',            # Use Season_enc instead
    'City_Code',         # Redundant with City_enc
    'Season_Code',       # Redundant with Season_enc
    'Year',              # Not useful for AQI prediction

    # ========== TARGETS (Not features) ==========
    'AQI_Bucket',        # Target category
    'AQI_Bucket_Code',   # Redundant target
    'AQI_Bucket_enc',    # Redundant target

    # ========== DATA LEAKAGE ==========
    'AQI_lag1',          # Using AQI to predict AQI
    'AQI_roll3',         # Using AQI to predict AQI
    'AQI_cityavg',       # Average AQI (leakage)
    'HighAQI_flag',      # Derived from AQI
    'HighAQI_count_month',  # Derived from AQI

    # ========== POLLUTANTS WITH NO SIGNAL (r ≈ 0) ==========
    # PM10 - All variants
    'PM10',              # r = +0.0008
    'PM10_lag1',         # r = +0.0002
    'PM10_roll3',        # r = -0.0014
    'PM10_cityavg',      # r = +0.0215

    # NO2 - All variants (keep NO instead)
    'NO2',               # r = +0.0055
    'NO2_lag1',          # r = -0.0006
    'NO2_roll3',         # r = +0.0043
    'NO2_cityavg',       # r = -0.0311

    # NOx - All variants
    'NOx',               # r = +0.0039
    'NOx_lag1',          # r = -0.0007
    'NOx_roll3',         # r = +0.0019
    'NOx_cityavg',       # r = -0.0447

    # NH3 - All variants
    'NH3',               # r = +0.0038
    'NH3_lag1',          # r = -0.0028
    'NH3_roll3',         # r = +0.0047
    'NH3_cityavg',       # r = +0.0264

    # Benzene - All variants
    'Benzene',           # r = -0.0062
    'Benzene_lag1',      # r = +0.0048
    'Benzene_roll3',     # r = +0.0003
    'Benzene_cityavg',   # r = -0.0296

    # Toluene - All variants
    'Toluene',           # r = -0.0037
    'Toluene_lag1',      # r = -0.0024
    'Toluene_roll3',     # r = -0.0068
    'Toluene_cityavg',   # r = -0.0732

    # Xylene - All variants
    'Xylene',            # r = -0.0012
    'Xylene_lag1',       # r = -0.0055
    'Xylene_roll3',      # r = -0.0041
    'Xylene_cityavg',    # r = +0.0548

    # ========== WEAK LAG FEATURES ==========
    'PM2.5_lag1',        # r = +0.0819 (too weak)
    'NO_lag1',           # r = +0.0708 (too weak)
    'SO2_lag1',          # r = +0.1158 (marginal, optional)
    'O3_lag1',           # r = +0.0374 (too weak)

    # ========== OPTIONAL: REMOVE CITYAVG IF SPACE NEEDED ==========
    # 'PM2.5_cityavg',   # r = +0.1373 (borderline, optional)
    # 'SO2_cityavg',     # r = +0.2186 (keep this)
    # 'NO_cityavg',      # r = +0.1335 (borderline, optional)
    # 'O3_cityavg',      # r = +0.1215 (borderline, optional)
]

print(f"\nRemoving {len(columns_to_remove)} columns:")

# Remove columns that exist in dataframe
columns_to_remove_actual = [col for col in columns_to_remove if col in df.columns]

for i, col in enumerate(sorted(columns_to_remove_actual), 1):
    print(f"  {i:2d}. {col}")

df_clean = df.drop(columns=columns_to_remove_actual, errors='ignore')

print(f"\nAfter: {df_clean.shape[1]} columns")
print(f"Shape: {df_clean.shape}")

columns_to_remove = [
    # ========== IDENTIFIERS ==========
    'City', 'Date', 'Season', 'City_Code', 'Season_Code', 'Year',

    # ========== TARGETS ==========
    'AQI_Bucket', 'AQI_Bucket_Code', 'AQI_Bucket_enc',

    # ========== DATA LEAKAGE ==========
    'AQI_lag1', 'AQI_roll3', 'AQI_cityavg', 'HighAQI_flag', 'HighAQI_count_month',

    # ========== POLLUTANTS WITH NO SIGNAL ==========
    'PM10', 'PM10_lag1', 'PM10_roll3', 'PM10_cityavg',
    'NO2', 'NO2_lag1', 'NO2_roll3', 'NO2_cityavg',
    'NOx', 'NOx_lag1', 'NOx_roll3', 'NOx_cityavg',
    'NH3', 'NH3_lag1', 'NH3_roll3', 'NH3_cityavg',
    'Benzene', 'Benzene_lag1', 'Benzene_roll3', 'Benzene_cityavg',
    'Toluene', 'Toluene_lag1', 'Toluene_roll3', 'Toluene_cityavg',
    'Xylene', 'Xylene_lag1', 'Xylene_roll3', 'Xylene_cityavg',

    # ========== WEAK LAG FEATURES ==========
    'PM2.5_lag1', 'NO_lag1', 'SO2_lag1', 'O3_lag1'
]

# ================================
# 2. Check which columns exist in df
# ================================
columns_to_remove_actual = [col for col in columns_to_remove if col in df.columns]

print(f"\nRemoving {len(columns_to_remove_actual)} columns:")
for i, col in enumerate(sorted(columns_to_remove_actual), 1):
    print(f"  {i:2d}. {col}")

# ================================
# 3. Drop the columns
# ================================
df_clean = df.drop(columns=columns_to_remove_actual, errors='ignore')

print(f"\nAfter removal: {df_clean.shape[1]} columns")
print(f"Shape: {df_clean.shape}")

# ================================
# 4. Drop remaining NaNs (from lag/rolling features)
# ================================
df_clean = df_clean.dropna()
print(f"Shape after dropping NaNs: {df_clean.shape}")

save_path = "/content/drive/MyDrive/smog_project/processed/cleaned_data_ml.csv"
df_clean.to_csv(save_path, index=False)
print(f"\nCleaned dataset saved to: {save_path}")

