# -*- coding: utf-8 -*-
"""Lasso&LightGBM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6DDwS5vCCF7o62E_IT_tXaZHdYLnbCb
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

dataset_path = "/content/drive/MyDrive/smog_project/processed/cleaned_data_ml.csv"
df = pd.read_csv(dataset_path)

X = df.drop(columns=['AQI']).values
y = df['AQI'].values

# Shuffle and split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

lasso_model = Lasso(alpha=0.1)  # You can tune alpha
lasso_model.fit(X_train, y_train)

y_train_pred = lasso_model.predict(X_train)
y_test_pred = lasso_model.predict(X_test)

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

import lightgbm as lgb

lgb_model = lgb.LGBMRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=7,
    random_state=42
)
lgb_model.fit(X_train, y_train)

y_train_pred_lgb = lgb_model.predict(X_train)
y_test_pred_lgb = lgb_model.predict(X_test)

evaluate(y_train, y_train_pred_lgb, "Train LightGBM")
evaluate(y_test, y_test_pred_lgb, "Test LightGBM")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Predictions min:", y_test_pred_lgb.min(), "max:", y_test_pred_lgb.max())

