# -*- coding: utf-8 -*-
"""Preprocessing&Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIBYN3WBDai-g1BYL3arSzSrGlztobwf
"""

from google.colab import drive
drive.mount('/content/drive')

# ===============================
# Advanced Preprocessing & Feature Engineering
# ===============================

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

# ------------------------------
# Load merged dataset (from previous step)
# ------------------------------
merged_path = "/content/drive/MyDrive/smog_project/processed/Merged_AQ_Processed.csv"
df = pd.read_csv(merged_path)

# Convert date column
df['Date'] = pd.to_datetime(df['Date'])

# 1. Standardize City names
# ------------------------------
df['City'] = df['City'].str.strip().str.title()

# ------------------------------
# 2. Time-based features
# ------------------------------
df['Weekday'] = df['Date'].dt.weekday         # 0 = Monday
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Year'] = df['Date'].dt.year

def get_season(month):
    if month in [12, 1, 2]: return 'Winter'
    elif month in [3, 4, 5]: return 'Summer'
    elif month in [6, 7, 8]: return 'Monsoon'
    else: return 'Post-Monsoon'
df['Season'] = df['Month'].apply(get_season)

# Encode season as categorical number
le_season = LabelEncoder()
df['Season_enc'] = le_season.fit_transform(df['Season'])

# Define pollutant columns
pollutants = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene','AQI']

for col in pollutants:
    # Previous day value
    df[f'{col}_lag1'] = df.groupby('City')[col].shift(1)
    # 3-day rolling mean
    df[f'{col}_roll3'] = df.groupby('City')[col].rolling(window=3, min_periods=1).mean().reset_index(0, drop=True)

# Average pollutant per city
city_avg = df.groupby('City')[pollutants].transform('mean')
city_avg.columns = [f'{c}_cityavg' for c in city_avg.columns]
df = pd.concat([df, city_avg], axis=1)

# Count of high-AQI days (>100) per city per month
df['HighAQI_flag'] = (df['AQI'] > 100).astype(int)
high_aqi_counts = df.groupby(['City','Year','Month'])['HighAQI_flag'].transform('sum')
df['HighAQI_count_month'] = high_aqi_counts

le_city = LabelEncoder()
df['City_enc'] = le_city.fit_transform(df['City'])

# Encode AQI_Bucket if exists
if 'AQI_Bucket' in df.columns:
    le_bucket = LabelEncoder()
    df['AQI_Bucket_enc'] = le_bucket.fit_transform(df['AQI_Bucket'])

numeric_cols = df.select_dtypes(include=['float64','int64']).columns.tolist()
numeric_cols = [c for c in numeric_cols if c not in ['Year','Month','Day','Weekday','City_enc','AQI_Bucket_enc']]
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

print("Dataset shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nMissing values per column:\n", df.isnull().sum())
print("\nData types:\n", df.dtypes)
print("\nStatistical summary:\n", df.describe())

# ---------- Distribution of AQI ----------
plt.figure(figsize=(10,6))
sns.histplot(df['AQI'], bins=50, kde=True, color='skyblue')
plt.title("Distribution of AQI")
plt.xlabel("AQI")
plt.ylabel("Count")
plt.show()

# ---------- Distribution of pollutants ----------
pollutants = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']
plt.figure(figsize=(15,10))
for i, col in enumerate(pollutants):
    plt.subplot(4,3,i+1)
    sns.histplot(df[col], bins=50, kde=True, color='lightgreen')
    plt.title(col)
plt.tight_layout()
plt.show()

# ---------- Boxplots of AQI by City ----------
plt.figure(figsize=(12,6))
top_cities = df['City'].value_counts().head(10).index.tolist()
sns.boxplot(x='City', y='AQI', data=df[df['City'].isin(top_cities)])
plt.title("AQI distribution across top 10 cities")
plt.xticks(rotation=45)
plt.show()

# ---------- Correlation Heatmap ----------
plt.figure(figsize=(12,10))
corr_cols = ['AQI'] + pollutants
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Heatmap: AQI and Pollutants")
plt.show()

# ---------- Time Series Trends (Example: AQI over time for top cities) ----------
plt.figure(figsize=(14,6))
for city in top_cities:
    city_df = df[df['City']==city]
    city_df = city_df.sort_values('Date')
    plt.plot(city_df['Date'], city_df['AQI'], label=city)
plt.title("AQI Trends Over Time (Top 10 Cities)")
plt.xlabel("Date")
plt.ylabel("AQI")
plt.legend()
plt.show()

if 'AQI_Bucket' in df.columns:
    plt.figure(figsize=(8,5))
    sns.countplot(data=df, x='AQI_Bucket', order=df['AQI_Bucket'].value_counts().index)
    plt.title("AQI Bucket Distribution")
    plt.show()

selected_features = ['AQI','PM2.5','PM10','NO2','CO','SO2','O3']
sns.pairplot(df[selected_features], kind='scatter', diag_kind='kde')
plt.suptitle("Pairplot: AQI vs Key Pollutants", y=1.02)
plt.show()

from scipy.stats import zscore
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
z_scores = np.abs(df[numeric_cols].apply(zscore))
outliers = (z_scores > 3).sum()
print("\nNumber of extreme outliers (|z|>3) per column:\n", outliers)

processed_path = "/content/drive/MyDrive/smog_project/processed/air_quality_ml_ready.csv"
df.to_csv(processed_path, index=False)
print(f"Processed dataset saved to {processed_path}")
print("Columns now available for ML:", df.columns.tolist())

