# -*- coding: utf-8 -*-
"""RandomForestTuned&Untuned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cd6YKNr512-qILJG32vUkphbTDoiNyFt
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

processed_path = "/content/drive/MyDrive/smog_project/processed/cleaned_data_ml.csv"
df = pd.read_csv(processed_path)

X = df.drop(columns=['AQI']).values
y = df['AQI'].values  # use real AQI

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

rf_model = RandomForestRegressor(
    n_estimators=200,   # number of trees
    max_depth=None,     # let trees grow fully
    random_state=42,
    n_jobs=-1           # use all CPU cores
)
rf_model.fit(X_train, y_train)

y_train_pred = rf_model.predict(X_train)
y_test_pred = rf_model.predict(X_test)

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Test predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

"""tuned Random Forest"""

rf_model = RandomForestRegressor(
    n_estimators=200,       # number of trees
    max_depth=15,           # limit depth to reduce overfitting
    min_samples_split=10,   # min samples to split a node
    min_samples_leaf=5,     # min samples per leaf
    max_features='sqrt',    # number of features considered at each split
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_train_pred = rf_model.predict(X_train)
y_test_pred = rf_model.predict(X_test)

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Test predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

