# -*- coding: utf-8 -*-
"""XGBoost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnxAVy5xi28LwLMpTEtq2hm2egPEVcHv
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

processed_path = "/content/drive/MyDrive/smog_project/processed/cleaned_data_ml.csv"
df = pd.read_csv(processed_path)

X = df.drop(columns=['AQI']).values
y = df['AQI'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

y_train_pred = xgb_model.predict(X_train)
y_test_pred = xgb_model.predict(X_test)

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)
X = df_shuffled.drop(columns=['AQI']).values
y = df_shuffled['AQI'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

y_train_pred = xgb_model.predict(X_train)
y_test_pred = xgb_model.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))  # compute RMSE manually
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

# Evaluate
evaluate(y_train, y_train_pred, "Train")
evaluate(y_test, y_test_pred, "Test")

print("Test AQI min:", y_test.min(), "max:", y_test.max())
print("Predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

"""XGBoost with log-transformed AQI"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

df_shuffled = df.sample(frac=1, random_state=42).reset_index(drop=True)
X = df_shuffled.drop(columns=['AQI']).values
y = df_shuffled['AQI'].values

y_log = np.log1p(y)  # log(1 + AQI) to handle zeros

X_train, X_test, y_train_log, y_test_log = train_test_split(
    X, y_log, test_size=0.2, random_state=42)

xgb_model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train_log)

y_train_pred_log = xgb_model.predict(X_train)
y_test_pred_log = xgb_model.predict(X_test)

y_train_pred = np.expm1(y_train_pred_log)  # reverse log(1 + AQI)
y_test_pred = np.expm1(y_test_pred_log)

y_train_real = np.expm1(y_train_log)
y_test_real = np.expm1(y_test_log)

def evaluate(y_true, y_pred, label="Data"):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    print(f"{label} - MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

evaluate(y_train_real, y_train_pred, "Train")
evaluate(y_test_real, y_test_pred, "Test")

print("Test AQI min:", y_test_real.min(), "max:", y_test_real.max())
print("Predictions min:", y_test_pred.min(), "max:", y_test_pred.max())

